Place.create!(name: "some place", address: "some address")
Place.create!(name: "another place", address: "another address")
Place.create!(name: "fake place", address: "fake address")
Place.create!(name: "new place", address: "new address")
Place.create!(name: "old place", address: "old address")
